### ISSUE TITLE
Cule on CUDA 11.1 + and  latest pytorch 1.8

### ISSUE THREAD

**Issue by Denys88** [NVlabs/cule#23]
I just bought new 3090 and want to run CULE

**Comment by ifrosio** [comment]
Did you try the prescribed installation?

**Comment by chutaklee** [comment]
> Did you try the prescribed installation?

Sadly it doesn't work. I encountered similar issues when running codes from [DeepSpeed](https://github.com/microsoft/DeepSpeedExamples). Reckon it's a CUDA11 problem.

```
> python setup.py install
Warning: Could not find nvcc in path. Compiling with default support for all architectures.This may result in exceedingly long startup times during initialization on the GPU.
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    runtime = Runtime()
  File "/home/lee/dl/cule/examples/utils/runtime.py", line 150, in __init__
    path = self._locate()['lib64']
  File "/home/lee/dl/cule/examples/utils/runtime.py", line 194, in _locate
    raise EnvironmentError('The CUDA %s path could not be located in %s' % (k, v))
OSError: The CUDA home path could not be located in :/usr/local/cuda-11.1

> which nvcc
/usr/local/cuda-11.1/bin/nvcc
```

**Comment by Denys88** [comment]
I dig deeper into it.
1) sm_30 is not supported in 11.1 cuda any more (nvcc fatal   : Value 'sm_30' is not defined for option 'gpu-architecture'
)
2) If remove sm_30 I'll get a lot of warnings like:
/cule/cule/atari/accessors.hpp(264): warning: calling a __host__ function("std::__cxx11::basic_string<char,     ::std::char_traits<char> , ::std::allocator<char> > ::~basic_string") from a __host__ __device__ function("cule::atari::rom::~rom [subobject]") is not allowed

It builds but I get error in the end when try to run:
'undefined symbol: cudaMemcpyAsync'
And I belive a reason why I get it is that it just doesn't work at sm_30.

**Comment by luchris429** [comment]
is there any particular reason this issue was closed? Is there no intention to support CUDA 11.1+, or was there a solution?

**Comment by mimoralea** [comment]
@Denys88

Did you get through this `cudaMemcpyAsync` issue? Any hints?

**Comment by Denys88** [comment]
@mimoralea 
I definitely fixed it but it was more than year ago . Let me try to build again.

**Comment by mimoralea** [comment]
I got almost there and created a repo to document the steps: https://github.com/mimoralea/cule

I had to re-write a new dockerfile: https://github.com/mimoralea/cule/blob/master/envs/Dockerfile

I got to building and running it, but it appears the latest AMPERE+ GPUs are not fully compatible. At least without the right compilers...
