### ISSUE TITLE
Question about your infrastructure

### ISSUE THREAD

**Issue by Emerald01** [NVlabs/cule#31]
By briefly looking at your paper and your implementation, I am not pretty clear about your basic design. Is the environment step function running at CPU and then you have GPU threads to handle a tricky data rendering pipeline, or GPU also handles the step function update (i.e., state, action, reward data updating and generation) so CPU is in general doing nothing concrete? Since from your figure in README, it looks like CPU is in charge of step function, and then GPU is handling data transfer.

Thank you

**Comment by ifrosio** [comment]
The CPU doesn’t do anything but schedule kernels. The GPU is doing everything to update both the state and frame buffers, as described in the paper - please have a look at the figure in the paper showing how we use the GPU to run both the TIA instructions and the rendering operations. The figure in the readme shows the typical situation where states are indeed updated on the CPU - CuLE avoids this by moving Atari emulation on the GPU.
